In [6]:
import numpy as np 

In [7]:
mylist = [1,2,3]


In [8]:
type(mylist)

list

In [9]:
np.array(mylist)

array([1, 2, 3])

In [10]:
mymatrix = [[1,2,3],[4,5,6],[7,8,9]]
mymatrix
np.array(mymatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.zeros(9)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [13]:
np.zeros((9,9))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [14]:
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [15]:
np.linspace(0,10,4)

array([  0.        ,   3.33333333,   6.66666667,  10.        ])

In [16]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [18]:
np.random.rand(4,4)

array([[ 0.07986431,  0.0078082 ,  0.85206871,  0.4103971 ],
       [ 0.58147578,  0.29220583,  0.00424922,  0.03262347],
       [ 0.41019379,  0.79102115,  0.26103606,  0.47453772],
       [ 0.62901856,  0.90425112,  0.42938272,  0.86838541]])

In [20]:
np.random.randn(4,4)

array([[ 0.73958977, -2.11675809,  1.17269183, -1.93842683],
       [ 0.75275303, -0.15098125, -1.10676098, -1.44220502],
       [ 0.01463932, -1.11678769,  0.08972185, -0.84189973],
       [-0.58646954,  0.27923905, -2.09049752,  0.3913059 ]])

In [23]:
np.random.randint(0,100,(4,4))

array([[96,  4, 48, 53],
       [30, 42, 80, 46],
       [50, 33, 46, 87],
       [78, 35, 31, 50]])

In [24]:
np.random.seed(19)
np.random.rand(3)

array([ 0.0975336 ,  0.76124972,  0.24693797])

In [25]:
ar = np.arange(0,25)

In [26]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ar.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ranar = np.random.randint(0,101,10)

In [30]:
ranar

array([52, 74, 31, 66, 56, 22, 34,  5, 97, 10])

In [31]:
ranar.max()

97

In [32]:
ranar.min()

5

In [33]:
ranar.argmax()

8

In [35]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
ar.shape

(25,)

In [37]:
ar.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
ar.shape

(25,)