In [1]:
import numpy as np

In [2]:
ar = np.arange(0,11)

In [3]:
ar[5]

5

In [4]:
ar[1:3]

array([1, 2])

In [5]:
ar[0:5] = 100

In [6]:
ar

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
ar = np.arange(0,11)

In [9]:
sliceofar = ar[0:5]

In [10]:
sliceofar

array([0, 1, 2, 3, 4])

In [11]:
sliceofar[:]=88
sliceofar

array([88, 88, 88, 88, 88])

In [12]:
ar

array([88, 88, 88, 88, 88,  5,  6,  7,  8,  9, 10])

In [16]:
ar2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [18]:
ar2d.shape

(3, 3)

In [19]:
ar2d[:1,:1]

array([[5]])

In [20]:
ar = np.arange(0,11)

In [21]:
ar > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [22]:
boolar = ar >4

In [23]:
ar[boolar]

array([ 5,  6,  7,  8,  9, 10])

In [24]:
ar[ar > 4]

array([ 5,  6,  7,  8,  9, 10])